FROM golang:1.14
RUN wget https://pkg.contrastsecurity.com/contrast-service-release/2.17.3/linux-amd64/contrast-service
RUN wget https://pkg.contrastsecurity.com/go-agent-release/0.8.0/linux-amd64/contrast-go   
RUN chmod u+x contrast-service
RUN chmod u+x contrast-go